### ISSUE TITLE
Page 5, Red vs Teal.  Does the data really support the conclusions reached without needing additional hypothetical justification?

### ISSUE THREAD

**Issue by compsoft-developer** [SagnikAdusumilli/COVID-Vaccine-Analysis#1]
The text refers to red being pre-vaccination, the legend on the graph says the opposite.
![screenshot 5](https://user-images.githubusercontent.com/65431359/164971104-e654af72-5235-454b-8a4f-e08f9feef5a8.jpg)

**Comment by SagnikAdusumilli** [comment]
@compsoft-developer Good point. I should have used Difference in Differences or Propensity score matching as those methods would suit the data more. This was an university assignment where I had to use linear regression so it was not the best approach. I plan to update the method section by using DID or propensity score matching.

As for the legend on the graph: It shows the total number of cases per age group. But later on the paper it appears that the average fatal cases per age group decreased after vaccines were introduced. I think the total fatal cases increased because vaccines were distributed on older age groups first and because more infections were happening in the younger age groups

Thanks
